// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByvBhCZeCBv7WjmY63TlTnI-lUyUqZ85s',
    appId: '1:1039764634745:web:dd7079cef22ff125b7a8a8',
    messagingSenderId: '1039764634745',
    projectId: 'crudfirebasestore',
    authDomain: 'crudfirebasestore.firebaseapp.com',
    storageBucket: 'crudfirebasestore.appspot.com',
    measurementId: 'G-9JTE8Z1YGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2HGfL6B70En-hpIblBC9ZJFxJfIHEnG8',
    appId: '1:1039764634745:android:bd05a27a34c243e4b7a8a8',
    messagingSenderId: '1039764634745',
    projectId: 'crudfirebasestore',
    storageBucket: 'crudfirebasestore.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM957Imp9DPZBQwrPbvRre7spG7NO-rxI',
    appId: '1:1039764634745:ios:b7dd37d5fa6c7569b7a8a8',
    messagingSenderId: '1039764634745',
    projectId: 'crudfirebasestore',
    storageBucket: 'crudfirebasestore.appspot.com',
    iosClientId: '1039764634745-8vqud64fsja3d7h3v7k8ef76650t8gu8.apps.googleusercontent.com',
    iosBundleId: 'com.crud.app',
  );
}
